"use strict";
const $=id=>document.getElementById(id);
const CHARSETS={uppercase:"ABCDEFGHIJKLMNOPQRSTUVWXYZ",lowercase:"abcdefghijklmnopqrstuvwxyz",numbers:"0123456789",symbols:"!@#$%^&*()_+-=[]{}|;:,.<>?/~"};
const AMBIGUOUS="O0Il1";
const el={output:$("passwordOutput"),length:$("length"),lengthValue:$("lengthValue"),uppercase:$("uppercase"),lowercase:$("lowercase"),numbers:$("numbers"),symbols:$("symbols"),ambiguous:$("ambiguous"),noRepeats:$("noRepeats"),exclude:$("excludeChars"),generate:$("generateButton"),regenerate:$("regenerateButton"),copy:$("copyPassword"),toggle:$("togglePassword"),strength:$("strengthText"),fill:$("strengthFill"),entropy:$("infoEntropy"),entropyCard:$("infoEntropyCard"),infoLength:$("infoLength"),charset:$("infoCharset"),multipleCount:$("multipleCount"),multiple:$("generateMultiple"),copyAll:$("copyAll"),results:$("multipleResults"),theme:$("themeToggle"),install:$("installButton"),toast:$("toast")};
let batch=[],deferredInstallPrompt=null,masked=false;\nconst hasCrypto=typeof crypto!=="undefined"&&typeof crypto.getRandomValues==="function";
function secureRandomInt(max){if(!hasCrypto)throw Error("Secure random generation is unavailable in this browser.");if(!Number.isInteger(max)||max<=0)throw Error("Invalid random range.");const limit=0x100000000-(0x100000000%max),v=new Uint32Array(1);do crypto.getRandomValues(v);while(v[0]>=limit);return v[0]%max}
function cleanGroup(group){let value=group;if(el.ambiguous.checked)value=[...value].filter(c=>!AMBIGUOUS.includes(c)).join("");const excluded=new Set([...el.exclude.value]);return [...value].filter(c=>!excluded.has(c)).join("")}
function getGroups(){const groups=[];if(el.uppercase.checked)groups.push(cleanGroup(CHARSETS.uppercase));if(el.lowercase.checked)groups.push(cleanGroup(CHARSETS.lowercase));if(el.numbers.checked)groups.push(cleanGroup(CHARSETS.numbers));if(el.symbols.checked)groups.push(cleanGroup(CHARSETS.symbols));return groups.filter(Boolean)}
function getCharset(){return [...new Set(getGroups().join(""))].join("")}
function violatesRepeat(p){for(let i=1;i<p.length;i++)if(p[i]===p[i-1])return true;return false}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=secureRandomInt(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
function generatePassword(){const length=Number(el.length.value),groups=getGroups(),charset=getCharset();if(!charset)throw Error("Select at least one character type.");if(groups.length>length)throw Error("Increase the password length to cover every selected character type.");const make=()=>{const chars=groups.map(g=>g[secureRandomInt(g.length)]);while(chars.length<length){let c;do c=charset[secureRandomInt(charset.length)];while(el.noRepeats.checked&&chars.at(-1)===c&&charset.length>1);chars.push(c)}return shuffle(chars).join("")};for(let i=0;i<100;i++){const p=make();if(!el.noRepeats.checked||!violatesRepeat(p))return p}return make()}
function entropy(p){return p.length*Math.log2(Math.max(getCharset().length,1))}
function strength(e){if(e<40)return["Very weak",20];if(e<60)return["Weak",40];if(e<80)return["Good",60];if(e<110)return["Strong",80];return["Excellent",100]}
function updateStats(){const set=getCharset(),p=el.output.value,e=p?entropy(p):Number(el.length.value)*Math.log2(Math.max(set.length,1));const [label,pct]=p?strength(e):["—",0];el.lengthValue.textContent=el.length.value;el.charset.textContent=set.length;el.strength.textContent=label;el.fill.style.width=pct+"%";el.entropy.textContent=e.toFixed(1)+" bits";el.entropyCard.textContent=e.toFixed(1)+" bits";el.infoLength.textContent=p.length||el.length.value}
function renderPassword(p){el.output.value=p;el.output.style.webkitTextSecurity=masked?"disc":"none";el.toggle.textContent=masked?"◎":"◉";el.toggle.setAttribute("aria-label",masked?"Show password":"Hide password");updateStats()}
function notify(m){el.toast.textContent=m;el.toast.classList.add("show");clearTimeout(notify.timer);notify.timer=setTimeout(()=>el.toast.classList.remove("show"),2200)}
function generateMain(){try{renderPassword(generatePassword())}catch(e){notify(e.message)}}
async function copyText(value){if(!value)return notify("Generate a password first.");try{await navigator.clipboard.writeText(value)}catch{const a=document.createElement("textarea");a.value=value;a.style.position="fixed";a.style.opacity="0";document.body.appendChild(a);a.select();document.execCommand("copy");a.remove()}notify("Password copied.")}
function generateBatch(){try{batch=Array.from({length:Number(el.multipleCount.value)},generatePassword);el.results.replaceChildren();batch.forEach((p,i)=>{const row=document.createElement("div");row.className="multiple-item";const n=document.createElement("span");n.className="batch-number";n.textContent=String(i+1).padStart(2,"0");const code=document.createElement("code");code.textContent=p;const b=document.createElement("button");b.className="mini-button";b.type="button";b.textContent="Copy";b.onclick=()=>copyText(p);row.append(n,code,b);el.results.appendChild(row)});el.copyAll.disabled=!batch.length;notify(batch.length+" passwords generated.")}catch(e){notify(e.message)}}
function toggleTheme(){const dark=document.documentElement.classList.toggle("dark");el.theme.textContent=dark?"☀":"☾";localStorage.setItem("blssnvj21-theme",dark?"dark":"light")}
function loadTheme(){const s=localStorage.getItem("blssnvj21-theme"),dark=s==="dark"||(s===null&&matchMedia("(prefers-color-scheme: dark)").matches);document.documentElement.classList.toggle("dark",dark);el.theme.textContent=dark?"☀":"☾"}
function init(){loadTheme();updateStats();if(!hasCrypto){el.generate.disabled=true;el.regenerate.disabled=true;el.multiple.disabled=true;notify("This browser does not provide secure random generation.");return}generateMain();el.length.oninput=updateStats;[el.uppercase,el.lowercase,el.numbers,el.symbols,el.ambiguous,el.noRepeats,el.exclude].forEach(i=>i.addEventListener("input",()=>{updateStats();generateMain()}));el.generate.onclick=generateMain;el.regenerate.onclick=generateMain;el.copy.onclick=()=>copyText(el.output.value);el.toggle.onclick=()=>{masked=!masked;renderPassword(el.output.value)};el.multiple.onclick=generateBatch;el.copyAll.onclick=()=>copyText(batch.join("\n"));el.theme.onclick=toggleTheme;document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key==="Enter"){e.preventDefault();generateMain()}});window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstallPrompt=e;el.install.classList.remove("hidden")});el.install.onclick=()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();deferredInstallPrompt.userChoice.finally(()=>{deferredInstallPrompt=null;el.install.classList.add("hidden")})}};if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{})}
init();